const allHeroes = [
    {
        id: "cleopatra",
        name: "Cleopatra",
        image: "https://i.ibb.co/R76zC55/Unit-Cleopatra-fullbody.png",
        icon: "https://i.ibb.co/gW9JWs9/Unit-Cleopatra.png",
        backdrop: "egypt",
        stars: 5,
        heroClass: "great-leader",
        unit: "ranged",
        color: "yellow",
        abilityIcon: "https://i.ibb.co/YQStSbg/icon-hero-battle-ability-cleopatra.png",
        ascension: {
            10: [
                {
                    resource: "yellow_crest_common",
                    amount: 25
                }
            ],
            20: [
                {
                    resource: "yellow_crest_common",
                    amount: 30
                },
                {
                    resource: "yellow_crest_enhanced",
                    amount: 10
                },
                {
                    resource: "fragrant_potpourri",
                    amount: 2
                }
            ],
            30: [
                {
                    resource: "yellow_crest_common",
                    amount: 50
                },
                {
                    resource: "herbal_poultice",
                    amount: 1
                },
                {
                    resource: "shadow_dial",
                    amount: 2
                }
            ]
        },
        abilityName: "Pharaoh's Puppets",
        abilityDescription: "Directs the Eye of Horus at the biggest cluster of enemy units, making them attack their allies for <b>3.50s</b>. Enemy units under Cleopatra's control gain <b>35%</b> attack speed.",
        ability: [
            "3.50s,35%",
        ]
    },
    {
        id: "albert-einstein",
        name: "Albert Einstein",
        image: "https://i.ibb.co/ynd8zKQ/Unit-Albert-Einstein-fullbody.png",
        icon: "https://i.ibb.co/KyMqcy4/Unit-Albert-Einstein.png",
        backdrop: "modern",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/58zmYCj/icon-hero-battle-ability-alberteinstein.png",
        ascension: {
            10: [
                {
                    resource: "blue_crest_common",
                    amount: 25
                }
            ]
        },
    },
    {
        id: "benjamin-franklin",
        name: "Benjamin Franklin",
        image: "https://i.ibb.co/r303kP1/Unit-Benjamin-Franklin-fullbody.png",
        icon: "https://i.ibb.co/hf8S5Q2/Unit-Benjamin-Franklin.png",
        backdrop: "modern",
        stars: 5,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/vYg6gJp/icon-hero-battle-ability-benjaminfranklin.png",
    },
    {
        id: "julius-caesar",
        name: "Julius Caesar",
        image: "https://i.ibb.co/QNJdYVP/Unit-Julius-Caesar-fullbody.png",
        icon: "https://i.ibb.co/6stWLHM/Unit-Julius-Caesar.png",
        backdrop: "italy",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/TtD5WrH/icon-hero-battle-ability-juliuscaesar.png",
    },
    {
        id: "leonardo-da-vinci",
        name: "Leonardo Da Vinci",
        image: "https://i.ibb.co/nc0vKGm/Unit-Leonardo-Da-Vinci-fullbody.png",
        icon: "https://i.ibb.co/m6F5Kcq/Unit-Leonardo-Da-Vinci.png",
        backdrop: "renaissance",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/5TN70Vw/icon-hero-battle-ability-leonardodavinci.png",
    },
    {
        id: "marie-curie",
        name: "Marie Curie",
        image: "https://i.ibb.co/tcJrD6g/Unit-Marie-Curie-fullbody.png",
        icon: "https://i.ibb.co/KmP2KCS/Unit-Marie-Curie.png",
        backdrop: "windmill",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/pKNm8T1/icon-hero-battle-ability-mariecurie.png",
    },
    {
        id: "napoleon-bonaparte",
        name: "Napoleon Bonaparte",
        image: "https://i.ibb.co/0fcBfz2/Unit-Napoleon-Bonaparte-fullbody.png",
        icon: "https://i.ibb.co/C70jyDv/Unit-Napoleon-Bonaparte.png",
        backdrop: "baroque",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/JdVf6m5/icon-hero-battle-ability-napoleonbonaparte.png",
    },
    {
        id: "queen-elisabeth-i",
        name: "Queen Elisabeth I",
        image: "https://i.ibb.co/9sTMWx3/Unit-Queen-Elizabeth-I-fullbody.png",
        icon: "https://i.ibb.co/Y3McmdP/Unit-Queen-Elizabeth-I.png",
        backdrop: "windmill",
        stars: 5,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/SQ28gQ4/icon-hero-battle-ability-queenelizabethi.png",
    },
    {
        id: "sir-lancelot",
        name: "Sir Lancelot",
        image: "https://i.ibb.co/sP0tLqb/Unit-Sir-Lancelot-fullbody.png",
        icon: "https://i.ibb.co/ysbNz5Z/Unit-Sir-Lancelot.png",
        backdrop: "sunflower",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/L18zRfM/icon-hero-battle-ability-sirlancelot.png",
    },
    {
        id: "george-washington",
        name: "George Washington",
        image: "https://i.ibb.co/qCncwY7/Unit-George-Washington-fullbody.png",
        icon: "https://i.ibb.co/XyW87Gy/Unit-George-Washington.png",
        backdrop: "modern",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/8jQcmZr/icon-hero-battle-ability-georgewashington.png",
    },
    {
        id: "hercules",
        name: "Hercules",
        image: "https://i.ibb.co/KW1mYGb/Unit-Hercules-fullbody.png",
        icon: "https://i.ibb.co/YkhK0vj/Unit-Hercules.png",
        backdrop: "greek",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/YLhBVcd/icon-hero-battle-ability-hercules.png",
    },
    {
        id: "william-wallace",
        name: "William Wallace",
        image: "https://i.ibb.co/g3ZcSjZ/Unit-William-Wallace-fullbody.png",
        icon: "https://i.ibb.co/Ph5YcG9/Unit-William-Wallace.png",
        backdrop: "grass",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/Y27JQGr/icon-hero-battle-ability-williamwallace.png",
    },
    {
        id: "robin-hood",
        name: "Robin Hood",
        image: "https://i.ibb.co/sR4MSg6/Unit-Robin-Hood-fullbody.png",
        icon: "https://i.ibb.co/gPG4Tsr/Unit-Robin-Hood.png",
        backdrop: "grass",
        stars: 5,
        heroClass: "champion",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/SdCCYqQ/icon-hero-battle-ability-robinhood.png",
    },
    {
        id: "joan-of-arc",
        name: "Joan of Arc",
        image: "https://i.ibb.co/Gtyygpp/Unit-Joan-Of-Arc-fullbody.png",
        icon: "https://i.ibb.co/0Qwn1hP/Unit-Joan-Of-Arc.png",
        backdrop: "windmill",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/1dTQ0G0/icon-hero-battle-ability-joanofarc.png",
    },
    {
        id: "achilles",
        name: "Achilles",
        image: "https://i.ibb.co/F4c084L/Unit-Achilles-fullbody.png",
        icon: "https://i.ibb.co/9rKb9rW/Unit-Achilles.png",
        backdrop: "greek",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/JyNDb8b/icon-hero-battle-ability-achilles.png",
    },
    {
        id: "abraham-lincoln",
        name: "Abraham Lincoln",
        image: "https://i.ibb.co/sjxYsqK/Unit-Abraham-Lincoln-fullbody.png",
        icon: "https://i.ibb.co/LZbLBsy/Unit-Abraham-Lincoln.png",
        backdrop: "modern",
        stars: 5,
        heroClass: "great-leader",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/1XdrmWD/icon-hero-battle-ability-abrahamlincoln.png",
    },
    {
        id: "medusa",
        name: "Medusa",
        image: "https://i.ibb.co/McffnfJ/Unit-Medusa-fullbody.png",
        icon: "https://i.ibb.co/1XzrhWp/Unit-Medusa.png",
        backdrop: "greek",
        stars: 5,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/W6ggm5T/icon-hero-battle-ability-medusa.png",
    },
    {
        id: "nikola-tesla",
        name: "Nikola Tesla",
        image: "https://i.ibb.co/HDVCCjs/Unit-Nikola-Tesla-fullbody.png",
        icon: "https://i.ibb.co/hDB4KJs/Unit-Nikola-Tesla.png",
        backdrop: "modern",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "",
    },
    {
        id: "menes",
        name: "Menes",
        image: "https://i.ibb.co/7CffsCZ/Unit-Menes-fullbody.png",
        icon: "https://i.ibb.co/8K3Xrxk/Unit-Menes.png",
        backdrop: "egypt",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/vZGJ54P/icon-hero-battle-ability-menes.png",
        ascension: {
            10: [
                {
                    resource: "red_crest_common",
                    amount: 15
                }
            ]
        },
    },
    {
        id: "ramses-ii",
        name: "Ramses II",
        image: "https://i.ibb.co/z62D9kH/Unit-Ramses-II-fullbody.png",
        icon: "https://i.ibb.co/SQCJsDr/Unit-Ramses-II.png",
        backdrop: "",
        stars: 4,
        heroClass: "",
        unit: "",
        abilityIcon: "https://i.ibb.co/HzbJMZn/icon-hero-battle-ability-ramsesii.png",
    },
    {
        id: "spartacus",
        name: "Spartacus",
        image: "https://i.ibb.co/RSCmSN0/Unit-Spartacus-fullbody.png",
        icon: "https://i.ibb.co/rw1x3w7/Unit-Spartacus.png",
        backdrop: "italy",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/6FcC3qy/icon-hero-battle-ability-spartacus.png",
    },
    {
        id: "confucius",
        name: "Confucius",
        image: "",
        icon: "https://i.ibb.co/vH8GtMd/Unit-Confucius.png",
        backdrop: "china",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/6sm7pGf/icon-hero-battle-ability-confuzius.png",
    },
    {
        id: "hatshepsut",
        name: "Hatshepsut",
        image: "https://i.ibb.co/Zx34J4y/Unit-Hatshepsut-fullbody.png",
        icon: "https://i.ibb.co/rxwhxrt/Unit-Hatshepsut.png",
        backdrop: "egypt",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/7WDXxRB/icon-hero-battle-ability-hatshepsut.png",
    },
    {
        id: "jane-austen",
        name: "Jane Austen",
        image: "https://i.ibb.co/ypHGCjh/Unit-Jane-Austen-fullbody.png",
        icon: "https://i.ibb.co/DVKXpVt/Unit-Jane-Austen.png",
        backdrop: "modern",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/xfXWSFX/icon-hero-battle-ability-janeausten.png",
    },
    {
        id: "louis-xiv",
        name: "Louis XIV",
        image: "https://i.ibb.co/KDHG5rM/Unit-Louis-XIV-fullbody.png",
        icon: "https://i.ibb.co/S5kHK56/Unit-Louis-XIV.png",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/8Xpw5Jh/icon-hero-battle-ability-louisxiv.png",
    },
    {
        id: "ludwig-van-beethoven",
        name: "Ludwig Van Beethoven",
        image: "https://i.ibb.co/7b7LNns/Unit-Ludwigvan-Beethoven-fullbody.png",
        icon: "https://i.ibb.co/h8sy232/Unit-Ludwigvan-Beethoven.png",
        backdrop: "renaissance",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/WKqJhbD/icon-hero-battle-ability-ludwigvanbeethoven.png",
    },
    {
        id: "margaret-i-of-denmark",
        name: "Margaret I of Denmark",
        image: "https://i.ibb.co/B3SnnZ0/Unit-Margaret-IOf-Denmark-fullbody.png",
        icon: "https://i.ibb.co/7GJVr1t/Unit-Margaret-IOf-Denmark.png",
        backdrop: "snow",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/8cktk16/icon-hero-battle-ability-margaretofdenmark.png",
    },
    {
        id: "plato",
        name: "Plato",
        image: "",
        icon: "https://i.ibb.co/BwDBcLV/Unit-Plato.png",
        backdrop: "greek",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/YtG0L2T/icon-hero-battle-ability-plato.png",
    },
    {
        id: "pocahontas",
        name: "Pocahontas",
        image: "https://i.ibb.co/1XXKs8b/Unit-Pocahontas-fullbody.png",
        icon: "https://i.ibb.co/rMfhr8g/Unit-Pocahontas.png",
        backdrop: "grass",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/Rv3hL64/icon-hero-battle-ability-pocahontas.png",
    },
    {
        id: "vincent-van-gogh",
        name: "Vincent Van Gogh",
        image: "https://i.ibb.co/zJSsHzq/Unit-Vincent-Van-Gogh-fullbody.png",
        icon: "https://i.ibb.co/6PJK1tz/Unit-Vincent-Van-Gogh.png",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/yhvN4Kj/icon-hero-battle-ability-vincentvangogh.png",
    },
    {
        id: "tomoe-gozen",
        name: "Tomoe Gozen",
        image: "https://i.ibb.co/FWF6fZg/Unit-Tomoe-Gozen-fullbody.png",
        icon: "https://i.ibb.co/K5wn5BD/Unit-Tomoe-Gozen.png",
        backdrop: "",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/3kV2rdP/icon-hero-battle-ability-tomoegozen.png",
    },
    {
        id: "thomas-alva-edison",
        name: "Thomas Alva Edison",
        image: "https://i.ibb.co/4Z1spgG/Unit-Edison-fullbody.png",
        icon: "https://i.ibb.co/N3XTMrY/Unit-Thomas-Alva-Edison.png",
        backdrop: "modern",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/yN4S7js/icon-hero-battle-ability-thomasalvaedison.png",
    },
    {
        id: "attila-the-hun",
        name: "Attila The Hun",
        image: "https://i.ibb.co/WGRXD2P/Unit-Attila-The-Hun-fullbody.png",
        icon: "https://i.ibb.co/RgmRNBN/Unit-Attila-The-Hun.png",
        backdrop: "grass",
        stars: 4,
        heroClass: "commander",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/SrvN7pT/icon-hero-battle-ability-attilathehun.png",
    },
    {
        id: "charlemagne",
        name: "Charlemagne",
        image: "https://i.ibb.co/DrM5fCT/Unit-Charlemagne-fullbody.png",
        icon: "https://i.ibb.co/njK2F5t/Unit-Charlemagne.png",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/CnjCvwL/icon-hero-battle-ability-charlemagne.png",
    },
    {
        id: "dartagnan",
        name: "D'artagnan",
        image: "https://i.ibb.co/bKPPZdM/Unit-DArtagnan-fullbody.png",
        icon: "https://i.ibb.co/rtkt5RN/Unit-DArtagnan.png",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/gdCjS4m/icon-hero-battle-ability-dartagnan.png",
    },
    {
        id: "king-minos",
        name: "King Minos",
        image: "https://i.ibb.co/F0HXVRj/Unit-King-Minos-fullbody.png",
        icon: "https://i.ibb.co/TT971jZ/Unit-King-Minos.png",
        backdrop: "greek",
        stars: 4,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/zxQV3z4/icon-hero-battle-ability-kingminos.png",
    },
    {
        id: "queen-boudicca",
        name: "Queen Boudicca",
        image: "https://i.ibb.co/yfmQn20/Unit-Queen-Boudicca-fullbody.png",
        icon: "https://i.ibb.co/zZpFR4g/Unit-Queen-Boudicca.png",
        backdrop: "grass",
        stars: 4,
        heroClass: "champion",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/cXfN15Y/icon-hero-battle-ability-queenboudicca.png",
    },
    {
        id: "miyamoto-musashi",
        name: "Miyamoto Musashi",
        image: "https://i.ibb.co/VMhb6tt/Unit-Miyamoto-Musashi-fullbody.png",
        icon: "https://i.ibb.co/1nfjv8K/Unit-Miyamoto-Musashi.png",
        backdrop: "china",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/PQ9NVp2/icon-hero-battle-ability-miyamotomusashi.png",
    },
    {
        id: "cyrus-the-great",
        name: "Cyrus the Great",
        image: "https://i.ibb.co/ySZkVrT/Unit-Cyrus-The-Great-fullbody.png",
        icon: "https://i.ibb.co/tztV1V4/Unit-Cyrus-The-Great.png",
        backdrop: "desert",
        stars: 3,
        heroClass: "commander",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/8zjPMNc/icon-hero-battle-ability-cyrusthegreat.png",
    },
    {
        id: "john-locke",
        name: "John Locke",
        image: "",
        icon: "https://i.ibb.co/4SRVWsr/Unit-John-Locke.png",
        backdrop: "renaissance",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/WBgJZjg/icon-hero-battle-ability-johnlocke.png",
    },
    {
        id: "karl-marx",
        name: "Karl Marx",
        image: "https://i.ibb.co/vHqHFQG/Unit-Karl-Marx-fullbody.png",
        icon: "https://i.ibb.co/8dFPbyk/Unit-Karl-Marx.png",
        backdrop: "sunflower",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/92ysZGV/icon-hero-battle-ability-karlmarx.png",
    },
    {
        id: "mansa-musa",
        name: "Mansa Musa",
        image: "https://i.ibb.co/KsZP6h1/Unit-Mansa-Musa-fullbody.png",
        icon: "https://i.ibb.co/3vRXTwM/Unit-Mansa-Musa.png",
        backdrop: "desert",
        stars: 3,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/nz2MChC/icon-hero-battle-ability-mansamusa.png",
    },
    {
        id: "marco-polo",
        name: "Marco Polo",
        image: "https://i.ibb.co/mJb2m68/Unit-Marco-Polo-fullbody.png",
        icon: "https://i.ibb.co/GVGbN0c/Unit-Marco-Polo.png",
        backdrop: "renaissance",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/tLfdFMH/icon-hero-battle-ability-marcopolo.png",
    },
    {
        id: "oracle-of-dephi",
        name: "Oracle of Dephi",
        image: "https://i.ibb.co/LJ8Q4Df/Unit-Oracleof-Dephi-fullbody.png",
        icon: "https://i.ibb.co/yfVDY8j/Unit-Oracleof-Dephi.png",
        backdrop: "greek",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/sJfbMPk/icon-hero-battle-ability-oracleofdelphi.png",
    },
    {
        id: "ada-lovelace",
        name: "Ada Lovelace",
        image: "https://i.ibb.co/601YTTg/Unit-Ada-Lovelace-fullbody.png",
        icon: "https://i.ibb.co/V34PJRL/Unit-Ada-Lovelace.png",
        backdrop: "sunflower",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/8DBYQkv/icon-hero-battle-ability-adalovelace.png",
    },
    {
        id: "artemisia-i-of-caria",
        name: "Artemisia I of Caria",
        image: "https://i.ibb.co/JKc45NC/Unit-Artemisia-IOf-Caria-fullbody.png",
        icon: "https://i.ibb.co/FW1mTX5/Unit-Artemisia-IOf-Caria.png",
        backdrop: "desert",
        stars: 3,
        heroClass: "champion",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/6vCqSPS/icon-hero-battle-ability-artemisiaiofcaria.png",
    },
    {
        id: "pythagoras",
        name: "Pythagoras",
        image: "https://i.ibb.co/mtGKN86/Unit-Pythagoras-fullbody.png",
        icon: "https://i.ibb.co/JxjdHzt/Unit-Pythagoras.png",
        backdrop: "greek",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/0nwBWqL/icon-hero-battle-ability-pythagoras.png",
    },
    {
        id: "hermann-the-cheruscan",
        name: "Hermann the Cheruscan",
        image: "https://i.ibb.co/6g9yY53/Unit-Hermann-The-Cheruscan-fullbody.png",
        icon: "",
        backdrop: "grass",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/bJCqT5g/icon-hero-battle-ability-hermannthecheruscan.png",
    },
    {
        id: "inanna",
        name: "Inanna",
        image: "https://i.ibb.co/5K3jQpz/Unit-Inanna-fullbody.png",
        icon: "https://i.ibb.co/nM23SNy/Unit-Inanna.png",
        backdrop: "desert",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/MfX8TpM/icon-hero-battle-ability-inanna.png",
    },
    {
        id: "otto-von-bismarck",
        name: "Otto Von Bismarck",
        image: "https://i.ibb.co/QrqX7h9/Unit-Otto-Von-Bismarck-fullbody.png",
        icon: "https://i.ibb.co/KxP2n4c/Unit-Otto-Von-Bismarck.png",
        backdrop: "baroque",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/dGY1j8G/icon-hero-battle-ability-ottovonbismarck.png",
    },
    {
        id: "ulysses-s-grant",
        name: "Ulysses S. Grant",
        image: "https://i.ibb.co/KyWP5vM/Unit-Ulysses-SGrant-fullbody.png",
        icon: "https://i.ibb.co/9GZVR5V/Unit-Ulysses-SGrant.png",
        backdrop: "modern",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/Cs82Nnq/icon-hero-battle-ability-ulyssessgrant.png",
    },
    {
        id: "ashoka-the-great",
        name: "Ashoka the Great",
        image: "https://i.ibb.co/CQ81tWB/Unit-Ashoka-The-Great-fullbody.png",
        icon: "https://i.ibb.co/3TjS6kC/Unit-Ashoka-The-Great.png",
        backdrop: "rainforest",
        stars: 3,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/tLVp9Yc/icon-hero-battle-ability-ashokathegreat.png",
    },
    {
        id: "leonidas-i",
        name: "Leonidas I.",
        image: "https://i.ibb.co/M5xR850/Unit-Leonidas-fullbody.png",
        icon: "https://i.ibb.co/BtdK1ZT/Unit-Leonidas.png",
        backdrop: "greek",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/FVKFXJw/icon-hero-battle-ability-leonidas.png",
    },
    {
        id: "william-tell",
        name: "William Tell",
        image: "https://i.ibb.co/bWjry2t/Unit-William-Tell-fullbody.png",
        icon: "https://i.ibb.co/FKzyGTY/Unit-William-Tell.png",
        backdrop: "windmill",
        stars: 3,
        heroClass: "champion",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/y69BCKB/icon-hero-battle-ability-williamtell.png",
    },
    {
        id: "maori-chief",
        name: "Maori Chief",
        image: "https://i.ibb.co/tPkRkRh/Unit-Maori-Chief-fullbody.png",
        icon: "https://i.ibb.co/56xgswG/Unit-Maori-Chief.png",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/wC5FQ9s/icon-hero-battle-ability-maorichief.png",
    },
    {
        id: "geisha",
        name: "Geisha",
        image: "https://i.ibb.co/7KPwTKc/Unit-Geisha-fullbody.png",
        icon: "https://i.ibb.co/JxG0p44/Unit-Geisha.png",
        backdrop: "china",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/tHWV6sr/icon-hero-battle-ability-geisha.png",
    },
    {
        id: "greek-mathematician",
        name: "Greek Mathematician",
        image: "https://i.ibb.co/xqWKj12/Unit-Greek-Mathematician-fullbody.png",
        icon: "https://i.ibb.co/fvVcJZR/Unit-Greek-Mathematician.png",
        backdrop: "greek",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/9N5SLHk/icon-hero-battle-ability-greekmathematician.png",
    },
    {
        id: "mayan-astronomer",
        name: "Mayan Astronomer",
        image: "https://i.ibb.co/fXxDMsz/Unit-Mayan-Astronomer-fullbody.png",
        icon: "https://i.ibb.co/nRNcgGP/Unit-Mayan-Astronomer.png",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/bXxwpjW/icon-hero-battle-ability-mayanastronomer.png",
    },
    {
        id: "roman-praetor",
        name: "Roman Praetor",
        image: "https://i.ibb.co/db8Zy1D/Unit-Roman-Praetor-fullbody.png",
        icon: "https://i.ibb.co/DYsRbqW/Unit-Roman-Praetor.png",
        backdrop: "italy",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/x6jrgpz/icon-hero-battle-ability-romanpraetor.png",
    },
    {
        id: "sioux-shaman",
        name: "Sioux Shaman",
        image: "https://i.ibb.co/4SK2M3z/Unit-Sioux-Shaman-fullbody.png",
        icon: "https://i.ibb.co/SNhDQKd/Unit-Sioux-Shaman.png",
        backdrop: "grass",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/fdkYjtD/icon-hero-battle-ability-siouxshaman.png",
    },
    {
        id: "tribal-healer",
        name: "Tribal Healer",
        image: "https://i.ibb.co/CmGHMT1/Unit-Tribal-Healer-fullbody.png",
        icon: "https://i.ibb.co/SfyHbCj/Unit-Tribal-Healer.png",
        backdrop: "grass",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/WxCBftB/icon-hero-battle-ability-tribalhealer.png",
    },
    {
        id: "roman-centurion",
        name: "Roman Centurion",
        image: "https://i.ibb.co/1LbNFk2/Unit-Roman-Centurion-fullbody.png",
        icon: "https://i.ibb.co/2ZybnKm/Unit-Roman-Centurion.png",
        backdrop: "italy",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/rGS5ChS/icon-hero-battle-ability-romancenturion.png",
    },
    {
        id: "egyptian-vizier",
        name: "Egyptian Vizier",
        image: "https://i.ibb.co/PTntZhG/Unit-Egyptian-Vizier-fullbody.png",
        icon: "https://i.ibb.co/82vXJhC/Unit-Egyptian-Vizier.png",
        backdrop: "egypt",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/DpcX8qT/icon-hero-battle-ability-egyptianvezir.png",
    },
    {
        id: "ninja",
        name: "Ninja",
        image: "https://i.ibb.co/Bs0JCJy/Unit-Ninja-fullbody.png",
        icon: "https://i.ibb.co/5FGtWhF/Unit-Ninja.png",
        backdrop: "china",
        stars: 2,
        heroClass: "champion",
        unit: "ranged",
        abilityIcon: "https://i.ibb.co/3ktz9Ys/icon-hero-battle-ability-ninja.png",
    },
    {
        id: "viking-jarl",
        name: "Viking Jarl",
        image: "https://i.ibb.co/WyPqpKR/Unit-Viking-Jarl-fullbody.png",
        icon: "https://i.ibb.co/2qZNnFm/Unit-Viking-Jarl.png",
        backdrop: "snow",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        abilityIcon: "https://i.ibb.co/dKCc523/icon-hero-battle-ability-vikingjarl.png",
    },
    {
        id: "aztec-tlacateccatl",
        name: "Aztec Tlacateccatl",
        image: "https://i.ibb.co/B6DYHSL/Unit-Aztec-Tlacateccatl-fullbody.png",
        icon: "https://i.ibb.co/SfWpLC1/Unit-Aztec-Tlacateccatl.png",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/RT72pjc/icon-hero-battle-ability-aztectlacateccatl.png",
    },
    {
        id: "hoplit",
        name: "Hoplit",
        image: "https://i.ibb.co/PxmYBPt/Unit-Hoplit-fullbody.png",
        icon: "https://i.ibb.co/2Fskp3Z/Unit-Hoplit.png",
        backdrop: "greek",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/4MdQpbh/icon-hero-battle-ability-hoplit.png",
    },
    {
        id: "jaguar-warrior",
        name: "Jaguar Warrior",
        image: "https://i.ibb.co/0YKxx7Y/Unit-Jaguar-Warrior-fullbody.png",
        icon: "https://i.ibb.co/LxBs4w6/Unit-Jaguar-Warrior.png",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/PZgndRz/icon-hero-battle-ability-jaguarwarrior.png",
    },
    {
        id: "japanese-shogun",
        name: "Japanese Shogun",
        image: "https://i.ibb.co/yhPYSdC/Unit-Japanese-Shogun-fullbody.png",
        icon: "https://i.ibb.co/MNjJygX/Unit-Japanese-Shogun.png",
        backdrop: "china",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/BwH4Rvq/icon-hero-battle-ability-japaneseshogun.png",
    },
    {
        id: "ottoman-general",
        name: "Ottoman General",
        image: "https://i.ibb.co/GRVKWHq/Unit-Ottoman-General-fullbody.png",
        icon: "https://i.ibb.co/0tRrd6Z/Unit-Ottoman-General.png",
        backdrop: "desert",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        abilityIcon: "https://i.ibb.co/rfFgfyv/icon-hero-battle-ability-ottomangeneral.png",
    },
    {
        id: "shaolin",
        name: "Shaolin",
        image: "https://i.ibb.co/HphGf9H/Unit-Shaolin-fullbody.png",
        icon: "https://i.ibb.co/rHsBj3R/Unit-Shaolin.png",
        backdrop: "china",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/c2WXYG2/icon-hero-battle-ability-shaolin.png",
    },
    {
        id: "jester",
        name: "Jester",
        image: "https://i.ibb.co/ydW9VN9/Unit-Jester-fullbody.png",
        icon: "https://i.ibb.co/zH0XK6d/Unit-Jester.png",
        backdrop: "windmill",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        abilityIcon: "https://i.ibb.co/30YgFD0/icon-hero-battle-ability-jester.png",
    },
    {
        id: "nubian-mercenary",
        name: "Nubian Mercenary",
        image: "https://i.ibb.co/KwgQH6v/Unit-Nubian-Mercenary-fullbody.png",
        icon: "https://i.ibb.co/yXDckB4/Unit-Nubian-Mercenary.png",
        backdrop: "desert",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/R6PWqxx/icon-hero-battle-ability-nubianmercenary.png",
    },
    {
        id: "viking-raider",
        name: "Viking Raider",
        image: "https://i.ibb.co/K6h6PVS/Unit-Viking-Raider-fullbody.png",
        icon: "https://i.ibb.co/VLHrfPN/Unit-Viking-Raider.png",
        backdrop: "snow",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        abilityIcon: "https://i.ibb.co/n6VtFD7/icon-hero-battle-ability-vikingraider.png",
    },
]

//https://i.ibb.co/L1CWfBs/Unit-Sun-Tzu-fullbody.png
//https://i.ibb.co/R07jTnK/Unit-Ragnar-Lodbrok-fullbody.png
//https://i.ibb.co/vLb3YkH/Unit-Qin-Shi-Huang-fullbody.png
//https://i.ibb.co/Fbm1CbG/Unit-Pakal-The-Great-fullbody.png
//https://i.ibb.co/VNwxfjf/Unit-Leif-Erikson-fullbody.png
//https://i.ibb.co/R2xZFXc/Unit-Lagertha-fullbody.png
//https://i.ibb.co/SJr8Y2z/Unit-Lady-Six-Sky-fullbody.png
//https://i.ibb.co/94Fy3XH/Unit-Hua-Mulan-fullbody.png

//https://i.ibb.co/44vpRWm/Unit-Hua-Mulan.png
//https://i.ibb.co/WfpWMxk/Unit-Pakal-The-Great.png
//https://i.ibb.co/Htxq2yR/Unit-Lady-Six-Sky.png
//https://i.ibb.co/7jfkJ65/Unit-Lagertha.png
//https://i.ibb.co/HxK2c70/Unit-Leif-Erikson.png
//https://i.ibb.co/Lr1znPM/Unit-Qin-Shi-Huang.png
//https://i.ibb.co/sgJKcz9/Unit-Ragnar-Lodbrok.png
//https://i.ibb.co/gV0nS91/Unit-Sun-Tzu.png
//https://i.ibb.co/h1tWDst/Unit-Unknown.png

//https://i.ibb.co/489Qd58/icon-hero-battle-ability-suntzu.png
//https://i.ibb.co/02gfp8J/icon-hero-battle-ability-montezumai.png
//https://i.ibb.co/kxnss6S/icon-hero-battle-ability-leiferikson.png
//https://i.ibb.co/Jpkn4Mz/icon-hero-battle-ability-ladysixsky.png
//https://i.ibb.co/1Gppy2q/icon-hero-battle-ability-scheherazade.png
//https://i.ibb.co/gZ0LtP1/icon-hero-battle-ability-saladin.png
//https://i.ibb.co/TktsnK2/icon-hero-battle-ability-lagertha.png
//https://i.ibb.co/mTLMMJB/icon-hero-battle-ability-ragnarlodbrok.png
//https://i.ibb.co/N6bpKD5/icon-hero-battle-ability-quinshihuang.png
//https://i.ibb.co/FDjwqhx/icon-hero-battle-ability-harunalrashid.png
//https://i.ibb.co/hs1gfNF/icon-hero-battle-ability-huamulan.png
//https://i.ibb.co/bFMJRkX/icon-hero-battle-ability-pakalthegreat.png

const levelsExperiences = {
    5: [
        100, 120, 140, 160, 170, 180, 190, 200, 210, 240, 250, 260, 260, 270, 280, 290, 290, 300, 300, 350, 350, 360, 370, 370, 380, 380, 390, 390, 400, 490 // the last is level 30 to 31
    ],
    4: [
        80, 99, 110, 120, 130, 140, 150, 160, 170
    ],
    3: [

    ],
    2: [

    ],
}

const heroClassIcons = {
    "champion": "https://i.ibb.co/rGsTmsn/icon-class-champion.png",
    "commander": "https://i.ibb.co/xL6jYNr/icon-class-commander.png",
    "genius": "https://i.ibb.co/J36xYv6/icon-class-genius.png",
    "great-leader": "https://i.ibb.co/sKQ3RsX/icon-class-great-leader.png",
    "manipulator": "https://i.ibb.co/Z8h0MkJ/icon-class-manipulator.png",
}

const heroClassNames = {
    "champion": "Champion",
    "commander": "Commander",
    "genius": "Genius",
    "great-leader": "Great Leader",
    "manipulator": "Manipulator",
}

const unitIcons = {
    "cavalry": "https://i.ibb.co/D7FWhy7/icon-flat-unit-cavalry.png",
    "heavy-infantry": "https://i.ibb.co/jD4r7DG/icon-flat-unit-heavy-infantry.png",
    "infantry": "https://i.ibb.co/YLY9PBK/icon-flat-unit-melee.png",
    "ranged": "https://i.ibb.co/KGbfZCw/icon-flat-unit-range.png",
    "siege": "https://i.ibb.co/wRkH9y3/icon-flat-unit-siege-units.png",
}

const unitNames = {
    "cavalry": "Cavalry",
    "heavy-infantry": "Heavy Infantry",
    "infantry": "Infantry",
    "ranged": "Ranged",
    "siege": "Siege",
}

const colorIcons = {
    "red": "https://i.ibb.co/LrNs29P/icon-colour-red.png",
    "yellow": "https://i.ibb.co/5vqb0XR/icon-colour-yellow.png",
    "green": "https://i.ibb.co/2qKmQZ5/icon-colour-green.png",
    "blue": "https://i.ibb.co/vQjqrqD/icon-colour-blue.png",
    "purple": "https://i.ibb.co/7S9B1Yk/icon-colour-purple.png",
}

const colorNames = {
    "yellow": "Yellow",
}

const backdrops = {
    "baroque": "https://i.ibb.co/1vzmXpr/hero-backdrop-baroque.png",
    "china": "https://i.ibb.co/3N16Gs6/hero-backdrop-china.png",
    "desert": "https://i.ibb.co/TBcxWMP/hero-backdrop-desert.png",
    "egypt": "https://i.ibb.co/prJxhdN/hero-backdrop-egypt.png",
    "grass": "https://i.ibb.co/8syD7nD/hero-backdrop-grass.png",
    "greek": "https://i.ibb.co/crgP1vG/hero-backdrop-greek.png",
    "italy": "https://i.ibb.co/MSY4Mb0/hero-backdrop-italy.png",
    "modern": "https://i.ibb.co/kBq0zjw/hero-backdrop-modern.png",
    "rainforest": "https://i.ibb.co/LYb9Yrc/hero-backdrop-rainforest.png",
    "renaissance": "https://i.ibb.co/bNdmcNR/hero-backdrop-renaissance.png",
    "snow": "https://i.ibb.co/1zhLYGR/hero-backdrop-snow.png",
    "sunflower": "https://i.ibb.co/34wsJxD/hero-backdrop-sunflower.png",
    "windmill": "https://i.ibb.co/PFsFVbz/hero-backdrop-windmill.png",
}

export { allHeroes, levelsExperiences, heroClassIcons, heroClassNames, unitIcons, unitNames, colorIcons, colorNames, backdrops };